### ISSUE TITLE
A way to remove jquery from the bundle

### ISSUE THREAD

**Issue by sergio91** [Genentech/pviz#6]
Is there a way to remove jquery from the bundle without breaking the code? I would like to just include jquery in the header.

**Comment by alexmasselot** [comment]
Hello Sergio,
Thanks for your ticket

Removing it from the bundle could have some side effects, so we should have a careful look at it.
However, you can also have a jQuery in your header that will be in the global namespace and should live without any problem with the one embedded into pviz (this latter one is local to the embedded package).

Is there any strong reason (other than loading twice jQuery in term of network bandwith) for removing jQuery from the bundle?

Alex

**Comment by sergio91** [comment]
Hello Alex,

We are worried that by using two versions of jquery we would get conflicts. So jquery in the bundle and our jquery in the header would not conflict with each other? is that correct?

Sergio

**Comment by alexmasselot** [comment]
Hei
It is not for me, in the various app we had. We in fact embed pviz in
angular (or other) application routinely, with their own jQuery.
With other libraries, we added the export of the embedded jQuery, to reuse
it elsewhere. But this is certainly not what you want.

Please let us know how this turn out for you

Alex

On Mon, May 11, 2015 at 12:14 PM, sergio91 <notifications@github.com> wrote:

> Hello Alex,
>
> We are worried that by using two versions of jquery we would get
> conflicts. So jquery in the bundle and our jquery in the header would not
> conflict with each other? is that correct?
>
> Sergio
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Genentech/pviz/issues/6#issuecomment-100847842>.
>



-- 
Alexandre Masselot

http://alexandre-masselot.blogspot.ch
<http://alexandre-masselot.blogspot.com/>/
<http://alexandre-masselot.blogspot.ch/>
http://mtroopgoeswest.blogspot.ch/

**Comment by alexmasselot** [comment]
I'll close the issue. But don't hesitate to call back if that's a show stopper

Alex
